### ISSUE TITLE
Add an admbrowser Wikipedia entry

### ISSUE THREAD

**Issue by stroobandt** [alandmoore/admbrowser#24]
An honour-full mention on <https://en.wikipedia.org/wiki/Comparison_of_lightweight_web_browsers> is certainly well deserved. This is especially the case because `admbrowser` is one of the few lightweight browsers employing WebEngine and perhaps the only one that is fully configurable.

Doing so, would attract more users, and by extension, more potential developers.

**Comment by alandmoore** [comment]
Thank you for the vote of confidence :-).  I would certainly be appreciative if someone who is a regular Wikipedia contributor wanted to add it to the list, but that's not really a rabbit-trail I want to go down right now.  I am not an active contributor there and I understand they have rules about self-promotion and notoriety that the project would need to meet.  

There are certainly many websites, wikis, and lists that the project could be mentioned on, but I would rather not raise project promotion issues as github issues, since it does not concern the code or functioning of the program.  This is in no way to dissuade users and fans of the project from promoting it as they see fit.
